[package]
name = "mdbook-tabbed"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33"
mdbook = "0.4"
pulldown-cmark = "0.9"
pulldown-cmark-to-cmark = "10.0"
serde_json = "1.0"
